[package]
description = "Platz.io SDK"
edition = "2021"
license-file = "LICENSE"
name = "platz-sdk"
repository = "https://github.com/platzio/sdk-rs"
version = "0.1.0"

[dependencies]
rust_decimal = "1.17.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
strum = {version = "0", features = ["derive"]}
