[package]
description = "Platz.io SDK"
edition = "2021"
license-file = "LICENSE"
name = "platz-sdk"
repository = "https://github.com/platzio/sdk-rs"
version = "0.2.0"

[dependencies]
anyhow = "1.0.56"
chrono = {version = "0.4.19", features = ["serde"]}
reqwest = {version = "0.11.4", features = ["rustls-tls", "json"]}
rust_decimal = "1.17.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
strum = {version = "0", features = ["derive"]}
url = "2.2.2"
uuid = {version = "0.8.2", features = ["serde"]}
